[package]
name = "jiknep-bot"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.93"
discord = { git = "https://github.com/Jiknep-Museum/discord-rs.git" }
serde = "1.0.215"
serde_derive = "1.0.215"
serde_json = "1.0.133"
